spring.application.name=Budly

jwt.secret=dkcbkjbkjbvkbcvnuhvgiungiuvretbunbkjfbuuvjhncrgeymgfbgyrigvbiqkwuntcrimdrhunkcgiuvhctdsgiucrge uxe
jwt.expirationMs=3600000
jwt.resetExpirationMs=600000


#mailjet configuration
spring.mail.host=in-v3.mailjet.com
spring.mail.port=587
spring.mail.username=3f6b0772aea733e8f78e39f605b00de6
spring.mail.password=d9fe9212cfcb08cb78c44c6d76a39eac
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true


#razorpay configuration
razorpay.key_id=rzp_test_SakroXEI5bzs7n
razorpay.key_secret=FvvgIRgNKhltQlKfSDt65Mgl

spring.datasource.url=jdbc:postgresql://localhost:5432/snap
spring.datasource.username=myuser
spring.datasource.password=2007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8094
server.address=0.0.0.0

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000
spring.data.redis.database=5
